import SessionProvider from "@/app/providers/SessionProvider";
import SideVav from '../widgets/layout/sidenav'
import Sidebar from "../widgets/layout/Sidebar";
// import { Nanum_Gothic } from "next/font/google";

// const nanum_gothic = Nanum_Gothic({
//   subsets: ["latin"],
//   weight: ["400", "700", "800"],
//   display: 'swap',
// });

export const metadata = {
  title: "naver social sign-in by next-auth",
  description: "Generated by create next app",
};

export default function WordLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Sidebar/>
      <div className="relative md:ml-64 bg-blueGray-100">
        {/* <AdminNavbar /> */}
        {/* Header */}
        {/* <HeaderStats /> */}
        <div className="px-4 md:px-10 mx-auto w-full -m-24">
          {children}
          {/* <FooterAdmin /> */}
        </div>
      </div>
    </div>
  )
}
