import SessionProvider from "@/app/providers/SessionProvider";
import SideVav from '../widgets/layout/sidenav'
// import { Nanum_Gothic } from "next/font/google";

// const nanum_gothic = Nanum_Gothic({
//   subsets: ["latin"],
//   weight: ["400", "700", "800"],
//   display: 'swap',
// });

export const metadata = {
  title: "naver social sign-in by next-auth",
  description: "Generated by create next app",
};

export default function WordLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <SideVav/>
      <div className="p-4 xl:ml-80">
        {children}
      </div>
    </div>
  )
}
