import SessionProvider from "@/app/providers/SessionProvider";
import Sidebar from "@/app/components/Sidebar/Sidebar";
import HeaderWord from "@/app/components/Headers/HeaderWord";
import FooterAdmin from "@/app/components/Footers/FooterAdmin";

// import { Nanum_Gothic } from "next/font/google";

// const nanum_gothic = Nanum_Gothic({
//   subsets: ["latin"],
//   weight: ["400", "700", "800"],
//   display: 'swap',
// });

export const metadata = {
  title: "naver social sign-in by next-auth",
  description: "Generated by create next app",
};

export default function WordLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Sidebar />
      <div className="relative md:ml-64 bg-blueGray-100">
        {/* Header */}
        <HeaderWord />
        <div className="px-4 md:px-10 mx-auto w-full">
          {children}
          <FooterAdmin />
        </div>
      </div>
    </>
  )
}
