import SessionProvider from "@/app/providers/SessionProvider";
import '@/app/style/tailwind.css'
// import { Nanum_Gothic } from "next/font/google";

// const nanum_gothic = Nanum_Gothic({
//   subsets: ["latin"],
//   weight: ["400", "700", "800"],
//   display: 'swap',
// });

export const metadata = {
  title: "naver social sign-in by next-auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <SessionProvider>
          <main style={{margin: '50px'}}>
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
