import SessionProvider from "@/app/providers/SessionProvider";
import '@/app/globals.css'
import "@fortawesome/fontawesome-free/css/all.min.css";
import '@/app/style/tailwind.css'
import { SWRProvider } from "./providers/SWRProvider";
// import { Nanum_Gothic } from "next/font/google";

// const nanum_gothic = Nanum_Gothic({
//   subsets: ["latin"],
//   weight: ["400", "700", "800"],
//   display: 'swap',
// });

export const metadata = {
  title: "naver social sign-in by next-auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <SessionProvider>
          <SWRProvider>
            <main>
              {children}
            </main>
          </SWRProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
